// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByHtOKU_EIDpJZ7gSenWF43nvz9j3YwMk',
    appId: '1:330928960235:android:1cdf74ac6324e2bb3104ae',
    messagingSenderId: '330928960235',
    projectId: 'mobile-final-3',
    authDomain: 'mobile-final-3.firebaseapp.com',
    storageBucket: 'mobile-final-3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByHtOKU_EIDpJZ7gSenWF43nvz9j3YwMk',
    appId: '1:330928960235:android:1cdf74ac6324e2bb3104ae',
    messagingSenderId: '330928960235',
    projectId: 'mobile-final-3',
    storageBucket: 'mobile-final-3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByHtOKU_EIDpJZ7gSenWF43nvz9j3YwMk',
    appId: '1:330928960235:android:1cdf74ac6324e2bb3104ae',
    messagingSenderId: '330928960235',
    projectId: 'mobile-final-3',
    storageBucket: 'mobile-final-3.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByHtOKU_EIDpJZ7gSenWF43nvz9j3YwMk',
    appId: '1:330928960235:android:1cdf74ac6324e2bb3104ae',
    messagingSenderId: '330928960235',
    projectId: 'mobile-final-3',
    storageBucket: 'mobile-final-3.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByHtOKU_EIDpJZ7gSenWF43nvz9j3YwMk',
    appId: '1:330928960235:android:1cdf74ac6324e2bb3104ae',
    messagingSenderId: '330928960235',
    projectId: 'mobile-final-3',
    authDomain: 'mobile-final-3.firebaseapp.com',
    storageBucket: 'mobile-final-3.firebasestorage.app',
  );
}