// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW0S1jaoe_AvFoiaeWh-v0se3gnfT7QXg',
    appId: '1:907297866335:web:3980266a0d4dbbf715d1ea',
    messagingSenderId: '907297866335',
    projectId: 'hwnoteapp',
    authDomain: 'hwnoteapp.firebaseapp.com',
    storageBucket: 'hwnoteapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1myqrM6cCHGZGNqxVIaj9W3OtJWYK-fM',
    appId: '1:907297866335:android:5fe8ae07e6ae864e15d1ea',
    messagingSenderId: '907297866335',
    projectId: 'hwnoteapp',
    storageBucket: 'hwnoteapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEmUks_jyoN5GXWSyJpkvSUXsLXui4dp8',
    appId: '1:907297866335:ios:aab7278ce7a6cea515d1ea',
    messagingSenderId: '907297866335',
    projectId: 'hwnoteapp',
    storageBucket: 'hwnoteapp.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEmUks_jyoN5GXWSyJpkvSUXsLXui4dp8',
    appId: '1:907297866335:ios:aab7278ce7a6cea515d1ea',
    messagingSenderId: '907297866335',
    projectId: 'hwnoteapp',
    storageBucket: 'hwnoteapp.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW0S1jaoe_AvFoiaeWh-v0se3gnfT7QXg',
    appId: '1:907297866335:web:df764f38db6ca21d15d1ea',
    messagingSenderId: '907297866335',
    projectId: 'hwnoteapp',
    authDomain: 'hwnoteapp.firebaseapp.com',
    storageBucket: 'hwnoteapp.firebasestorage.app',
  );
}